### ISSUE TITLE
Plans to continue the project?

### ISSUE THREAD

**Issue by fmerges** [cursive-works/wagtail-plotly#5]
Hello,
I would like to know if there are plans to continue and improve this project, or if it is going to stay like that... I just tried it with 4.1.2, and it works fine.
Any help needed? Translations?
Cheers!

**Comment by marts** [comment]
Hi @fmerges thanks for getting in touch. We don't have any grand plans for wagtail-plotly ... at one point I was going to expand it and try to add more plot blocks to match the capabilities of plotly. Unfortunately, I've not had time to do this. Great to hear it works with the latest Wagtail though. Any suggestions you have for it will be gladly received.
